package com.dealerops.core.common.exception;

public enum ErrorCode {
  VALIDATION(400),
  VIN_DUP(400),
  SOLD_PAIR_REQUIRED(400),
  WRONG_DEALER_OR_SOLD(400),
  UNAUTHORIZED(401),
  FORBIDDEN(403),
  NOT_FOUND(404),
  METHOD_NOT_ALLOWED(405),
  VERSION_CONFLICT(409),
  DUP_MEMBER(409),
  USERNAME_TAKEN(409),
  DISPLAY_NAME_TAKEN(409),
  EMAIL_TAKEN(409),
  PHONE_TAKEN(409),
  VEHICLE_ALREADY_LINKED(409),
  SOLD_LOCKED(409),
  CHECK_STALE(409),
  NOT_PASSED(409),
  LEAD_CLOSED(409),
  WORK_ORDER_CLOSED(409),
  WORK_ORDERS_OPEN(409),
  UNSUPPORTED_MEDIA_TYPE(415),
  INTERNAL_ERROR(500),
  AI_UNAVAILABLE(502),
  CATALOG_UNAVAILABLE(502);

  private final int httpStatus;

  ErrorCode(int httpStatus) {
    this.httpStatus = httpStatus;
  }

  public int getHttpStatus() {
    return httpStatus;
  }
}
