<script setup lang="ts">
import { ref,onMounted } from 'vue'
import AppLayout from '../layouts/AppLayout.vue'
import DataTable from '../components/DataTable.vue'
import FormDrawer from '../components/FormDrawer.vue'
import ConfirmDialog from '../components/ConfirmDialog.vue'
import PageState from '../components/PageState.vue'
import { adminApi } from '../api/admin'
const rows=ref<any[]>([]),members=ref<any[]>([]),total=ref(0),loading=ref(false),error=ref(''),tab=ref('dealers'),drawer=ref(false),memberDrawer=ref(false),confirm=ref(false),selected=ref<any>(); const form=ref({legalName:'',contactPhone:'',contactEmail:'',contactAddress:''}),member=ref({entraOid:'',displayName:''}),q=ref('')
async function load(){loading.value=true;error.value='';try{const r=await adminApi.dealers({q:q.value,page:0,size:10});rows.value=r.data.items||[];total.value=r.data.total||0}catch{error.value='Could not load dealerships.'}finally{loading.value=false}}
async function openMembers(row:any){selected.value=row;memberDrawer.value=true;const r=await adminApi.members(row.id,{page:0,size:10});members.value=(r.data.items||[]).map((x:any)=>({...x,legalName:row.legalName}))}
async function create(){await adminApi.createDealer(form.value);drawer.value=false;form.value={legalName:'',contactPhone:'',contactEmail:'',contactAddress:''};load()}
async function bind(){await adminApi.bind(selected.value.id,member.value);member.value={entraOid:'',displayName:''};await openMembers(selected.value);load()}
async function unbind(oid:string){await adminApi.unbind(selected.value.id,oid);confirm.value=false;await openMembers(selected.value);load()}
onMounted(load)
</script>
<template><AppLayout><div class="page"><div class="page-header"><div><h1>Admin</h1><span class="muted">Dealerships and members</span></div><el-button type="primary" @click="drawer=true">New dealership</el-button></div><el-tabs v-model="tab"><el-tab-pane label="Dealerships" name="dealers"><div class="filters"><el-input v-model="q" placeholder="Dealership name" clearable/><el-button @click="load">Search</el-button><el-button @click="q='';load()">Reset</el-button></div><PageState :loading="loading" :error="error" :empty="!loading&&!error&&!rows.length" empty-text="No dealerships yet." loading-text="Loading dealerships…"><DataTable :rows="rows" :total="total" :page="0"><el-table-column prop="legalName" label="Name"/><el-table-column label="Contact"><template #default="{row}">{{row.contactPhone}} · {{row.contactEmail}}</template></el-table-column><el-table-column prop="staffCount" label="Staff count"/></DataTable></PageState></el-tab-pane><el-tab-pane label="Members" name="members"><el-button @click="Promise.all(rows.map(openMembers))">Refresh members</el-button><el-table :data="members" style="margin-top:16px"><el-table-column prop="entraOid" label="Entra ID / email"/><el-table-column prop="legalName" label="Dealership"/><el-table-column prop="active" label="Status"/></el-table></el-tab-pane></el-tabs></div><FormDrawer title="New dealership" :visible="drawer" @close="drawer=false"><el-form label-position="top"><el-form-item label="Legal name"><el-input v-model="form.legalName"/></el-form-item><el-form-item label="Contact phone"><el-input v-model="form.contactPhone"/></el-form-item><el-form-item label="Contact email"><el-input v-model="form.contactEmail"/></el-form-item><el-form-item label="Contact address"><el-input v-model="form.contactAddress"/></el-form-item><el-button type="primary" @click="create">Create</el-button></el-form></FormDrawer><FormDrawer title="Staff" :visible="memberDrawer" @close="memberDrawer=false"><el-form label-position="top"><el-form-item label="Entra OID"><el-input v-model="member.entraOid"/></el-form-item><el-form-item label="Display name"><el-input v-model="member.displayName"/></el-form-item><el-button type="primary" @click="bind">Bind staff</el-button></el-form><el-table :data="members" style="margin-top:20px"><el-table-column prop="entraOid" label="Entra ID"/><el-table-column prop="displayName" label="Name"/><el-table-column label="Actions"><template #default="{row}"><el-button link @click="selected=row;confirm=true">Unbind</el-button></template></el-table-column></el-table></FormDrawer><ConfirmDialog :visible="confirm" title="Unbind staff" message="Remove this staff membership?" @cancel="confirm=false" @confirm="unbind(selected.entraOid)"/></AppLayout></template>
