<script setup lang="ts">
import { ref,onMounted,watch } from 'vue'
import AppLayout from '../layouts/AppLayout.vue';import AdWorkspace from '../components/AdWorkspace.vue';import PageState from '../components/PageState.vue';import { vehiclesApi } from '../api/vehicles';import { listingsApi } from '../api/listings'
const vehicles=ref<any[]>([]),selected=ref<any>(),listing=ref<any>({title:'',body:'',adKind:'CASH',medium:'ONLINE',version:0}),loading=ref(false),error=ref(''),saving=ref(false),checking=ref(false)
const loadVehicles=async()=>{const r=await vehiclesApi.list({page:0,size:10});vehicles.value=r.data.items||[]}
async function select(v:any){selected.value=v;loading.value=true;try{listing.value=(await listingsApi.get(v.id)).data}catch{error.value='Could not load listing.'}finally{loading.value=false}}
async function save(){saving.value=true;try{listing.value=(await listingsApi.save(selected.value.id,{...listing.value,version:listing.value.version||0})).data}catch(e){error.value='Could not load listing.'}finally{saving.value=false}}
async function check(){checking.value=true;try{listing.value={...listing.value,...(await listingsApi.check(listing.value.id,{version:listing.value.version})).data}}catch(e){if((e as any).response?.status===502){listing.value={...listing.value,checkStatus:'AI_UNAVAILABLE'}}else error.value='Could not load listing.'}finally{checking.value=false}}
async function ready(){listing.value=(await listingsApi.ready(listing.value.id,{version:listing.value.version})).data}
async function exportTxt(){const r=await listingsApi.export(listing.value.id,{version:listing.value.version});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='dealer-ad.txt';a.click();URL.revokeObjectURL(url)}
onMounted(loadVehicles);watch(()=>selected.value?.id,v=>{if(v){const q=new URLSearchParams(location.search).get('vehicleId');if(q&&!selected.value)select(v)}})
</script>
<template><AppLayout><div class="page"><div class="page-header"><div><h1>Ad compliance</h1><span class="muted">Check an advertisement before export</span></div></div><div class="ad-grid"><el-card><template #header>Vehicles</template><el-table :data="vehicles" @row-click="select"><el-table-column label="Vehicle"><template #default="{row}">{{row.modelYear}} {{row.make}} {{row.model}}</template></el-table-column><el-table-column prop="status" label="Status"/><el-table-column prop="checkStatus" label="Check status"/></el-table></el-card><PageState :loading="loading" :error="error" :empty="!selected" empty-text="Select a vehicle to start." loading-text="Loading listing…"><AdWorkspace v-model="listing"><template #actions><el-button @click="save" :loading="saving" :disabled="!selected">Save draft</el-button><el-button @click="check" :loading="checking" :disabled="!listing.id">Run check</el-button><el-button @click="ready" :disabled="listing.checkStatus!=='PASSED'">Mark ready</el-button><el-button @click="exportTxt" :disabled="listing.checkStatus!=='PASSED'">Export TXT</el-button></template><template #result><el-tag v-if="listing.checkStatus" :type="listing.checkStatus==='PASSED'?'success':listing.checkStatus==='BLOCKED'?'danger':'warning'">{{listing.checkStatus.replaceAll('_',' ')}}</el-tag><el-empty v-else description="Select a vehicle to start."/></template></AdWorkspace></PageState></div></div></AppLayout></template>
