<script setup lang="ts">
import { ref,onMounted } from 'vue'
import AppLayout from '../layouts/AppLayout.vue';import DataTable from '../components/DataTable.vue';import FormDrawer from '../components/FormDrawer.vue';import ConfirmDialog from '../components/ConfirmDialog.vue';import PageState from '../components/PageState.vue';import { customersApi } from '../api/customers';import { vehiclesApi } from '../api/vehicles';import { auditApi } from '../api/audit'
const rows=ref<any[]>([]),total=ref(0),page=ref(0),loading=ref(false),error=ref(''),drawer=ref(false),confirm=ref(false),selected=ref<any>(),vehicles=ref<any[]>([]),audit=ref<any[]>([]),form=ref<any>({name:'',email:'',phone:'',homeAddress:''}),filters=ref<any>({q:'',linked:''}),linkId=ref<number>()
const load=async()=>{loading.value=true;try{const r=await customersApi.list({...filters.value,page:page.value,size:10});rows.value=r.data.items||[];total.value=r.data.total||0}catch{error.value='Could not load customers.'}finally{loading.value=false}}
async function open(row?:any){selected.value=row;form.value=row?{...row}:{name:'',email:'',phone:'',homeAddress:''};drawer.value=true;if(row){const r=await customersApi.get(row.id);selected.value=r.data;form.value=r.data;const v=await vehiclesApi.list({status:'IN_STOCK',page:0,size:10});vehicles.value=(v.data.items||[]).filter((x:any)=>!x.linkedCustomerId)}}
async function save(){if(selected.value)await customersApi.update(selected.value.id,{...form.value,version:selected.value.version});else await customersApi.create(form.value);drawer.value=false;load()}
async function link(){await customersApi.link(selected.value.id,linkId.value);await open(selected.value);load()}
async function unlink(){await customersApi.unlink(selected.value.id,selected.value.linkedVehicles[0].id);confirm.value=false;await open(selected.value);load()}
async function loadAudit(){const r=await auditApi.list({entityType:'CUSTOMER',entityId:selected.value.id});audit.value=r.data.items||[]}
onMounted(load)
</script>
<template><AppLayout><div class="page"><div class="page-header"><div><h1>CRM</h1><span class="muted">Customers and linked vehicles</span></div><el-button type="primary" @click="open()">Add customer</el-button></div><div class="filters"><el-input v-model="filters.q" placeholder="Name / Email / Phone"/><el-select v-model="filters.linked" placeholder="Linked" clearable><el-option label="Linked" value="true"/><el-option label="Not linked" value="false"/></el-select><el-button @click="page=0;load()">Search</el-button><el-button @click="filters={q:'',linked:''};page=0;load()">Reset</el-button></div><PageState :loading="loading" :error="error" :empty="!loading&&!error&&!rows.length" empty-text="No customers match." loading-text="Loading customers…"><DataTable :rows="rows" :total="total" :page="page" @page="p=>{page=p;load()}"><el-table-column prop="name" label="Name"/><el-table-column prop="email" label="Email"/><el-table-column prop="phone" label="Phone"/><el-table-column label="Linked vehicle"><template #default="{row}">{{row.linkedVehicle?row.linkedVehicle.modelYear+' '+row.linkedVehicle.make+' '+row.linkedVehicle.model:'—'}}</template></el-table-column><template #actions="{row}"><el-button link @click="open(row)">Edit</el-button></template></DataTable></PageState></div><FormDrawer title="Customer" :visible="drawer" @close="drawer=false"><el-form label-position="top"><el-form-item v-for="key in ['name','email','phone','homeAddress']" :key="key" :label="key"><el-input v-model="form[key]"/></el-form-item><el-button type="primary" @click="save">Save</el-button><template v-if="selected"><el-divider/><el-select v-model="linkId" filterable placeholder="Link vehicle" style="width:100%"><el-option v-for="v in vehicles" :key="v.id" :label="v.modelYear+' '+v.make+' '+v.model" :value="v.id"/></el-select><el-button @click="link">Link vehicle</el-button><el-button v-if="selected.linkedVehicles?.length&&selected.linkedVehicles[0].status!=='SOLD'" @click="confirm=true">Unlink</el-button><el-divider/><el-button @click="loadAudit">Load audit</el-button><el-table v-if="audit.length" :data="audit"><el-table-column prop="action" label="Action"/><el-table-column prop="createdAt" label="When"/></el-table></template></el-form></FormDrawer><ConfirmDialog :visible="confirm" title="Unlink vehicle" message="Remove this vehicle link?" @cancel="confirm=false" @confirm="unlink"/></AppLayout></template>
